gantt
    dateFormat  YYYY-MM-DD HH:mm
axisFormat .
    title GDPR Scenario Visualization

    section Milestones
        [Now, 2500-12-31 23_59] :milestone, ct, 2382-02-19 02:04, 0d
    [StartProcessing, erni, emaildata, 2025-07-12 08_30] :milestone, id1, 2144-05-25 06:14, 0d
    [GiveConsent, erni, emaildata, 2025-07-12 08_20] :milestone, id2, 2025-07-12 08:20, 0d
    [WithdrawConsent, erni, emaildata, 2025-07-12 08_35] :milestone, id3, 2263-04-08 04:09, 0d

    section Legal Bases
    [Consent , erni , emaildata] :active, id4, 2025-07-12 08:20, 2263-04-08 04:09

    section Processing
    [Processing , erni , emaildata] :done, id5, 2144-05-25 06:14, 2382-02-19 02:04

    section DataBreach
    [No data] :crit, id6, 2025-07-12 08:20, 2025-07-12 08:20