gantt
    dateFormat  YYYY-MM-DD HH:mm
axisFormat .

    section Milestones
        [Now, 2025-07-15 08_31] :milestone, ct, 2310-10-25 12:55, 0d
    [StartProcessing, erni, emaildata, 2025-07-12 08_25] :milestone, id1, 2120-08-16 01:51, 0d
    [GiveConsent, erni, emaildata, 2025-07-12 08_20] :milestone, id2, 2025-07-12 08:20, 0d
    [GiveConsent, erni, emaildata, 2025-07-15 08_31] :milestone, id3, 2310-10-25 12:55, 0d
    [DataBreachDetected, erni, emaildata, 2025-07-12 08_30] :milestone, id4, 2215-09-20 19:23, 0d

    section Legal Bases
    [Consent , erni , emaildata] :active, id5, 2025-07-12 08:20, 2405-11-28 06:27
    [Consent , erni , emaildata] :active, id6, 2310-10-25 12:55, 2405-11-28 06:27

    section Processing
    [Processing , erni , emaildata] :done, id7, 2120-08-16 01:51, 2405-11-28 06:27

    section DataBreach
    [DataBreach , erni , emaildata] :crit, id8, 2215-09-20 19:23, 2405-11-28 06:27