gantt
    dateFormat  YYYY-MM-DD HH:mm
axisFormat .
    title GDPR Scenario Visualization

    section Milestones
        [Now, 2025-07-12 08_25] :milestone, ct, 2025-07-12 08:25, 0d
    [StartProcessing, erni, emaildata, 2025-07-12 08_25] :milestone, 1, 2025-07-12 08:25, 0d

    section Legal Bases
    [No data] :active, 1, 2025-07-12 08:25, 2025-07-12 08:25

    section Processing
    [Processing , erni , emaildata] :done, 1, 2025-07-12 08:25, 2263-04-08 04:12

    section DataBreach
    [No data] :crit, 1, 2025-07-12 08:25, 2025-07-12 08:25