import json
from pathlib import Path
import re
import logging
import shutil

from agentic_loop.models import TaskSpec
from agentic_loop.stats_utils import PurgeStats
from agentic_loop.utils.hard_tla_patch import extract_invariants_from_tla
from .trace_utils import parse_tlc_trace, tlc_trace_to_markdown_table
from .prompting import load_prompt_template, render_prompt
from .tlc_error_utils import classify_tlc_error

def save_tlc_log(log_dir, attempt_id, tlc_output):
    log_dir = Path(log_dir)
    log_dir.mkdir(parents=True, exist_ok=True)
    log_file = log_dir / f"attempt_{attempt_id}_tlc_output.txt"
    with open(log_file, "w", encoding="utf-8") as f:
        f.write(tlc_output)
    return str(log_file)

def load_skills(skills_json_path="skills.json"):
    with open(skills_json_path, encoding="utf-8") as f:
        return json.load(f)


def _coerce_module_dir(module_dir: Path | str) -> Path:
    if isinstance(module_dir, tuple):
        raise TypeError(
            "LoopConfig.module_dir must be path-like; tuple payloads are no longer supported."
        )
    try:
        resolved = Path(module_dir).expanduser().resolve()
    except TypeError as exc:
        raise TypeError("LoopConfig.module_dir must be path-like") from exc
    if not resolved.exists():
        raise FileNotFoundError(f"Module directory '{resolved}' not found.")
    if not resolved.is_dir():
        raise NotADirectoryError(f"Module directory '{resolved}' is not a directory.")
    return resolved


def _resolve_task_artifact(module_dir: Path, artifact: str) -> Path:
    artifact_path = Path(artifact)
    if artifact_path.is_absolute():
        return artifact_path

    direct = module_dir / artifact_path
    if direct.exists():
        return direct

    if artifact_path.parts and artifact_path.parts[0] == module_dir.name:
        stripped = Path(*artifact_path.parts[1:]) if len(artifact_path.parts) > 1 else Path()
        candidate = module_dir / stripped
        if candidate.exists():
            return candidate

    parent_candidate = module_dir.parent / artifact_path
    if parent_candidate.exists():
        return parent_candidate

    matches = [hit for hit in module_dir.rglob(artifact_path.name) if hit.as_posix().endswith(artifact_path.as_posix())]
    if matches:
        return matches[0]

    raise FileNotFoundError(
        f"Unable to locate artifact '{artifact}' relative to module directory '{module_dir}'."
    )


def validate_module_layout(task: TaskSpec, module_dir: Path | str) -> None:
    root = _coerce_module_dir(module_dir)

    # Always copy the bootstrap .cfg template to the destination
    bootstrap_cfg_template = Path(__file__).resolve().parent.parent / "default_bootstrap/BootstrapModule.cfg"
    cfg_target = root / task.cfg_file
    cfg_target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(bootstrap_cfg_template, cfg_target)
    logging.info(f"[Bootstrap] Copied .cfg config from template at {cfg_target}")

    # Always copy the bootstrap .tla template, with MODULE header rewritten
    bootstrap_tla_template = Path(__file__).resolve().parent.parent / "default_bootstrap/BootstrapModule.tla"
    tla_target = root / f"{task.module_name}.tla"
    with open(bootstrap_tla_template, "r", encoding="utf-8") as src:
        content = src.read()

    content = re.sub(
        r"---- MODULE .* ----",
        f"---- MODULE {task.module_name} ----",
        content,
        count=1
    )
    content = ("\\* AUTOGENERATED FROM BootstrapModule.tla. Replace or edit as needed.\n" + content)
    with open(tla_target, "w", encoding="utf-8") as f:
        f.write(content)
    logging.info(f"[Bootstrap] Copied TLA+ module from template at {tla_target}")

    # (Optional) Manifest file check
    manifest = root / "manifest.json"
    if not manifest.exists():
        logging.warning(
            f"Optional manifest.json not found in module directory '{root}'."
        )


def _write_module(module_dir: Path | str, module_name: str, spec_text: str, attempt_id: int) -> Path:
    """Ensure MODULE header matches snapshot filename."""
    module_dir = Path(module_dir)
    snapshot_name = f"{module_name}_attempt_{attempt_id}"
    snapshot_path = module_dir / f"{snapshot_name}.tla"
    lines = spec_text.strip().splitlines()
    if lines:
        lines[0] = f"---- MODULE {snapshot_name} ----"
    fixed_body = "\n".join(lines)
    # Save to latest main (optional, for backwards compat)
    target = module_dir / f"{module_name}.tla"
    target.write_text(fixed_body + "\n", encoding="utf-8")
    # Save to snapshot with correct header
    snapshot_path.write_text(fixed_body + "\n", encoding="utf-8")
    logging.info(
        f"[ModuleWrite] attempt={attempt_id} target={target} snapshot={snapshot_path}"
    )
    return snapshot_path




def purge_temp_modules(task_name: str, module_root: Path | str) -> PurgeStats:
    """Remove staged module directories for a task under ``module_root`` and report reclaimed space."""

    root = Path(module_root).expanduser().resolve()
    if not root.exists() or not root.is_dir():
        return PurgeStats()

    prefix = f"{task_name}_"
    removed = 0
    reclaimed_bytes = 0

    for candidate in list(root.iterdir()):
        if not candidate.is_dir() or not candidate.name.startswith(prefix):
            continue
        try:
            for file_path in candidate.rglob("*"):
                if file_path.is_file():
                    try:
                        reclaimed_bytes += file_path.stat().st_size
                    except OSError:
                        continue
            shutil.rmtree(candidate, ignore_errors=False)
            removed += 1
        except Exception as exc:
            logging.warning(
                f"Failed to purge staged module directory '{candidate}': {exc}",
                RuntimeWarning,
            )
    stats = PurgeStats(removed_directories=removed, reclaimed_bytes=reclaimed_bytes)
    if removed:
        logging.info(f"[ModuleCleanup] {stats.as_log_message()}")
    return stats


# --- Utility: Generate config file from TLA+ module and bootstrap config ---
def generate_cfg_for_tla(tla_path, bootstrap_cfg_path, out_cfg_path):
    with open(tla_path, encoding="utf-8") as f:
        tla_lines = f.readlines()

    constants_declared = set()
    for line in tla_lines:
        mconst = re.match(r"\s*CONSTANTS?\s+([a-zA-Z_][a-zA-Z0-9_, ]*)", line)
        if mconst:
            names = [x.strip() for x in mconst.group(1).split(",")]
            constants_declared.update(names)

    invariant_names = extract_invariants_from_tla(tla_lines)

    init_name, next_name = None, None
    for line in tla_lines:
        m = re.match(r"\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*==", line)
        if m:
            opname_l = m.group(1).lower()
            if opname_l == "init":
                init_name = m.group(1)
            elif opname_l == "next":
                next_name = m.group(1)

    with open(bootstrap_cfg_path, encoding="utf-8") as f:
        cfg_in = f.readlines()
    output_lines = []
    for l in cfg_in:
        if "INIT <InitPredicateName>" in l and init_name:
            output_lines.append(f"INIT {init_name}\n")
        elif "NEXT <NextPredicateName>" in l and next_name:
            output_lines.append(f"NEXT {next_name}\n")
        elif "INVARIANT <TypeOK or something>" in l:
            if "TypeOK" in invariant_names:
                output_lines.append("INVARIANT TypeOK\n")
        elif re.match(r"\s*INVARIANTS?", l, re.IGNORECASE):
            if invariant_names:
                output_lines.append("INVARIANTS\n")
                for inv in invariant_names:
                    output_lines.append(f"    {inv}\n")
        elif l.strip().startswith("CONSTANT") or l.strip().startswith("CONSTANTS"):
            if constants_declared:
                output_lines.append("CONSTANT " + ", ".join(constants_declared) + "\n")
        elif l.strip() == "CONSTANT":
            if constants_declared:
                output_lines.append("CONSTANT " + ", ".join(constants_declared) + "\n")
        else:
            if l.strip() != "" and not l.strip().startswith("*"):
                output_lines.append(l)
    with open(out_cfg_path, "w", encoding="utf-8") as f:
        for l in output_lines:
            f.write(l)
    return out_cfg_path



def write_violation_report(report_path, attempt_id, violated_inv, tla_inv_code, nl_req, trace, trace_lines, skill, tlc_log_path, llm_explanation=None, llm_plan=None):
    Path(report_path).parent.mkdir(parents=True, exist_ok=True)
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(f"# TLC Error/Violation Report\n\n")
        f.write(f"**Attempt:** {attempt_id}\n\n")
        f.write(f"**Detected Error Type (Skill):** `{skill['key']}`\n")
        f.write(f"**Skill Strategy:** {skill['strategy']}\n\n")
        f.write("## TLC Log File\n")
        f.write(f"[Full TLC log for this attempt]({tlc_log_path})\n\n")
        if violated_inv:
            f.write(f"**Violated Invariant:** `{violated_inv}`\n\n")
        f.write("## Invariant Definition\n")
        f.write(f"```tla\n{tla_inv_code}\n```\n")
        f.write("## Original Natural Language Requirement\n")
        f.write(f"{nl_req}\n\n")
        if trace_lines:
            f.write("## TLC Violation Trace (Markdown Table)\n")
            f.write(tlc_trace_to_markdown_table(trace_lines) + "\n\n")
        if trace:
            f.write("## TLC Raw Trace\n")
            f.write("```\n" + trace + "\n```\n")
        if llm_explanation:
            f.write("## LLM Explanation/Diagnosis\n")
            f.write(llm_explanation + "\n\n")
        if llm_plan:
            f.write("## LLM-Generated Repair Plan\n")
            f.write(llm_plan + "\n\n")

def generate_cfg_via_llm(module_snapshot, task, provider, attempt_id, prompts_dir, cfg_generation_template=None):
    """
    Generates a TLC .cfg file by prompting the LLM directly,
    instead of using the standard patch/process logic.
    """
    # Compose the input prompt for the LLM
    prompt_template = cfg_generation_template if cfg_generation_template is not None else load_prompt_template(prompts_dir, "cfg_generation")
    with open(module_snapshot, "r", encoding="utf-8") as f:
        tla_contents = f.read()
    llm_prompt = render_prompt(
        prompt_template,
        {
            "tla_module": tla_contents,
            "task_name": task.name,
            "task_requirements": task.requirement_text,
            "example_config": "",
        }
    )
    # Ask LLM to generate .cfg
    llm_response = provider.generate(llm_prompt, {"attempt_id": str(attempt_id), "phase": "generate_cfg"})
    # Write result to cfg file
    out_cfg_path = module_snapshot.with_suffix(".llm.cfg")
    with open(out_cfg_path, "w", encoding="utf-8") as f:
        f.write(llm_response)
    logging.info(f"[LLM-CFG] Wrote LLM-generated TLC config to {out_cfg_path}")
    return str(out_cfg_path)

# Compute case_metrics as before
def get_failure_classes_from_attempt(attempt):
    key = None
    output = getattr(attempt, "feedback_excerpt", None) or getattr(attempt, "status", None)
    if output:
        try:
            skills_db = load_skills("skills.json")
            key = classify_tlc_error(str(output), skills_db).get("key", "unknown")
        except Exception:
            key = "unknown"
    # Always surface unknown key now
    return [key] if key else []

